# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://github.com/sethreidnz/azure-devops-examples
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectFolder: 'banklite'
  buildOutputFolder: 'banklite/build'
  
steps:
## Run the npm install/build
- script: |
    # npm install
    # npm clean
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && npm run build && popd
## Copy the client to the staging directory
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(buildOutputFolder)' 
    contents: '**/*' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

## Archive the files into a zip file for publishing
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Fintech.CBS.BankLingo.zip'
    includeRootFolder: false

## Publish the zip file
- task: PublishBuildArtifacts@1
  inputs:
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/Fintech.CBS.BankLingo.zip'
    
